name: Publish role to Ansible Galaxy

on:
  release:
    types:
      - released

jobs:
  deploy:
    uses: telekom-mms/.github/.github/workflows/ansible-galaxy-role-publish.yml@main
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
