---
name: "test"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    services:
      grafana:
        image: grafana/grafana:latest@sha256:f9811e4e687ffecf1a43adb9b64096c50bc0d7a782f8608530f478b6542de7d5
        ports:
          - 3000:3000
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Python 3.8
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          pip install molecule[ansible] molecule-docker

      - name: Test with molecule
        run: |
          molecule --version
          molecule test
